testing fail

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -139,4 +139,22 @@ jobs:
           --request POST \
           https://api.github.com/repos/dataquest-dev/\
           dspace-ui-tests/actions/workflows/cron-test.yml/dispatches \
-          --data "{\"ref\":\"refs/heads/master\"}"
+          --data "{\"ref\":\"refs/heads/fail\"}"
+
+          # wait for it to start
+          sleep 30s
+
+          # get result of last job
+          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-ui-tests/actions/workflows/cron-test.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+
+          # while job did not finish, sleep
+          while [[ $RES == 'null' ]]; do
+            sleep 10s
+            RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-ui-tests/actions/workflows/cron-test.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          done;
+
+          # if last result is not success, return -1 and fail
+          if [[ $RES != 'success' ]]; then
+            echo $RES
+            exit 1
+          fi;
