Uncommented rest tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -155,8 +155,6 @@ jobs:
     timeout-minutes: 45
     if: '!inputs.IMPORT'
     steps:
-      - name: Check runner
-        run: echo "Self-hosted runner dspace-test-1 is now running this job"
       - name: Checkout Playwright tests
         uses: actions/checkout@v4
         with:
@@ -165,24 +163,18 @@ jobs:
           path: dspace-ui-tests
           token: ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}
 
-      - name: After checkout playwright
-        run: |
-          echo "UI Tests were checkouted, needs to copy json now"
-          ls -la dspace-ui-tests
-
       - name: Checkout main repository
         uses: actions/checkout@v4
         with:
-          path: main-repo
+          path: this-repository
 
-      - name: Copy config to UI tests repository
+      - name: Copy customer config to UI tests repository for merging
         run: |
-          cp main-repo/config/config.lindat.ui.tests.json dspace-ui-tests/customer-constants/
+          cp this-repository/config/config.lindat.ui.tests.json dspace-ui-tests/customer-constants/
 
       - name: test
         working-directory: dspace-ui-tests/scripts
         env:
-          PLAYWRIGHT_ARTIFACTS_DIR: /tmp/playwright-artifacts
           HOME_URL: https://dev-5.pc:8443/repository/
           NAME: DEFAULT
         run: |
@@ -195,38 +187,38 @@ jobs:
           CHOWN_DIR: ./
         if: ${{ always() }}
 
-  # rest-tests-after-deploy8:
-  #   runs-on: ubuntu-latest
-  #   needs: playwright-after-deploy8
-  #   timeout-minutes: 45
-  #   steps:
-  #     - name: run rest-tests
-  #       run: |
-  #         curl -H "Accept: application/vnd.github.everest-preview+json" \
-  #         -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
-  #         --request POST \
-  #         https://api.github.com/repos/dataquest-dev/\
-  #         dspace-rest-test/actions/workflows/run_unittests.yml/dispatches \
-  #         --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
+  rest-tests-after-deploy8:
+    runs-on: ubuntu-latest
+    needs: playwright-after-deploy8
+    timeout-minutes: 45
+    steps:
+      - name: run rest-tests
+        run: |
+          curl -H "Accept: application/vnd.github.everest-preview+json" \
+          -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
+          --request POST \
+          https://api.github.com/repos/dataquest-dev/\
+          dspace-rest-test/actions/workflows/run_unittests.yml/dispatches \
+          --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
 
-  #         # wait for it to start
-  #         sleep 30s
+          # wait for it to start
+          sleep 30s
 
-  #         # get result of last job
-  #         RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          # get result of last job
+          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
 
-  #         # while job did not finish, sleep
-  #         while [[ $RES == 'null' ]]; do
-  #           sleep 10s
-  #           RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
-  #         done;
+          # while job did not finish, sleep
+          while [[ $RES == 'null' ]]; do
+            sleep 10s
+            RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          done;
 
-  #         echo $RES
-  #         # if last result is not success, return -1 and fail
-  #         if [[ $RES != \"success\" ]]; then
-  #           echo "rest-tests have failed! check appropriate action run in the dspace-rest-test repository"
-  #           exit 1
-  #         fi;
+          echo $RES
+          # if last result is not success, return -1 and fail
+          if [[ $RES != \"success\" ]]; then
+            echo "rest-tests have failed! check appropriate action run in the dspace-rest-test repository"
+            exit 1
+          fi;
 
 
   playwright-after-import8:
