Removed unnecessary steps

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -167,34 +167,34 @@ jobs:
       INSTANCE: '8'
       CUSTOMER: 'customer/lindat'
     secrets: inherit
-    steps:
-      - name: run rest-tests
-        run: |
-          curl -H "Accept: application/vnd.github.everest-preview+json" \
-          -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
-          --request POST \
-          https://api.github.com/repos/dataquest-dev/\
-          dspace-rest-test/actions/workflows/run_unittests.yml/dispatches \
-          --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
+    # steps:
+    #   - name: run rest-tests
+    #     run: |
+    #       curl -H "Accept: application/vnd.github.everest-preview+json" \
+    #       -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
+    #       --request POST \
+    #       https://api.github.com/repos/dataquest-dev/\
+    #       dspace-rest-test/actions/workflows/run_unittests.yml/dispatches \
+    #       --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
 
-          # wait for it to start
-          sleep 30s
+    #       # wait for it to start
+    #       sleep 30s
 
-          # get result of last job
-          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+    #       # get result of last job
+    #       RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
 
-          # while job did not finish, sleep
-          while [[ $RES == 'null' ]]; do
-            sleep 10s
-            RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
-          done;
+    #       # while job did not finish, sleep
+    #       while [[ $RES == 'null' ]]; do
+    #         sleep 10s
+    #         RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+    #       done;
 
-          echo $RES
-          # if last result is not success, return -1 and fail
-          if [[ $RES != \"success\" ]]; then
-            echo "rest-tests have failed! check appropriate action run in the dspace-rest-test repository"
-            exit 1
-          fi;
+    #       echo $RES
+    #       # if last result is not success, return -1 and fail
+    #       if [[ $RES != \"success\" ]]; then
+    #         echo "rest-tests have failed! check appropriate action run in the dspace-rest-test repository"
+    #         exit 1
+    #       fi;
 
 
   playwright-after-import8:
